### PR TITLE
Round pixel values to 1dp.

### PR DESCRIPTION
**Pull request by callumacrae**
Should speed things up a bit.

### CODE REVIEW

**Comment by callumacrae** [comment]
@wagerfield Bump. Is this project still happening?

**Comment by callumacrae** [comment]
I think that's a no lol

**Comment by bluecrash** [comment]
lol

**Comment by dt1973** [comment]
Can any of you try and see if you can reach him via Twitter?

**Comment by ahoess** [comment]
You will need to update lines 400 and 401 in parallax.js 

Replace: 
`````
x += 'px';
y += 'px';
`````
With: (adjust 000's for rounding adjustment):
`````
x = Math.round(x*1000)/1000 + 'px';
y = Math.round(y*1000)/1000 + 'px';
`````

**Comment by RRorg** [comment]
Thank you for your input! I'll implement the suggested changes.

**Pull request closed without merging**
