### PR TITLE
Activating Travis/Git webhook, added FPSGraph example

### PR DESCRIPTION
**Pull request by xenyal**

### CODE REVIEW

**Comment by dt1973** [comment]
:+1:

**Comment by dt1973** [comment]
@xenyal using this were you able to test if @callumacrae's https://github.com/wagerfield/parallax/pull/90 helped with performance?

**Comment by xenyal** [comment]
@dt1973 it does not. JS by default does not have (by definition) true floating point numbers as they are all approximations in binary (from your OS's standpoint) hence why it displays a trivially long decimal. As an example, it's the same reason why CSS transitions for opacity will display up to 10+ decimals during a transition .

**Comment by xenyal** [comment]
Refer to (this)[http://steve.hollasch.net/cgindex/coding/ieeefloat.html] for more detailed clarification on floating point numbers vs their binary counterparts.

**Comment by callumacrae** [comment]
That's not relevant and it's also not the reason the numbers are so long. It's not a floating point error, it's just bizarrely precise.

My PR reduces the number of repaints required.

**Comment by xenyal** [comment]
@callumacrae There are no rerenders/repaints. Parallax acts on DOM objects, not canvas elements so small tweaks in CSS attributes are the only changes being made.

**Comment by dt1973** [comment]
Much obliged for the input guys!

**Pull request closed without merging**
